version: '3.7'

services:
  frontend:
    restart: always
    command: "npm run dev"
    build:
      context: './frontend'
    volumes:
      - ./frontend/:/root/frontend
    networks:
      - gate-tier
  backend:
    command: "go run main.go"
    restart: always
    build:
      context: './backend'
    volumes:
      - ./backend/:/go/src/github.com/pengliheng/golang-api/backend
    networks:
      - gate-tier
  nginx:
    restart: always
    build:
      context: './nginx'
    networks:
      - gate-tier
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx:/var/log/nginx/
    ports:
      - "80:80"
      - "8080:8080"
      - "1235:1235"

networks:
  gate-tier: